"""Deterministically compile a Mechanical execution script and run manifest."""

from __future__ import annotations

import base64
import json
import shutil
from pathlib import Path

from ansys_skill.compiler.plan import build_mechanical_plan
from ansys_skill.manifest import (
    add_artifact,
    environment_snapshot,
    initial_manifest,
    write_manifest,
)
from ansys_skill.paths import (
    prepare_output_dir,
    require_fresh_run_dir,
    resolve_input_path,
    safe_join,
)
from ansys_skill.schema import Mode, SimulationSpec, dump_normalized_yaml

_RUNTIME_DIRECTORY = Path(__file__).with_name("mechanical_runtime")
_RUNTIME_PARTS = ("compat.py", "scopes.py", "model.py", "artifacts.py", "run.py")
_SCRIPT_HEADER = '''# Generated by text-to-ansys. Do not edit this derived artifact.
from __future__ import print_function, unicode_literals

import base64
import json
import math
import os
import shutil
import traceback
import units

SENTINEL = "TEXT_TO_ANSYS_RESULT:"
PLAN = json.loads(base64.b64decode("__PLAN_BASE64__").decode("utf-8"))
RUN_DIRECTORY = os.path.abspath(getattr(os, "getcwdu", os.getcwd)())
TEXT_TYPE = type(u"")
FACE_SELECTIONS = []
CREATED = {"supports": {}, "loads": {}, "results": {}}
CREATED_SCOPES = {}
ANALYSIS_INFO = {}
OBJECT_TYPES = {}
'''
SCRIPT_TEMPLATE = _SCRIPT_HEADER + "\n\n" + "\n\n".join(
    (_RUNTIME_DIRECTORY / name).read_text(encoding="utf-8") for name in _RUNTIME_PARTS
)


def render_script(plan: dict[str, object]) -> str:
    compact = json.dumps(plan, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    encoded = base64.b64encode(compact.encode("utf-8")).decode("ascii")
    return SCRIPT_TEMPLATE.replace("__PLAN_BASE64__", encoded)


def compile_simulation(
    spec: SimulationSpec, spec_path: Path, output_dir: str | Path
) -> dict[str, object]:
    require_fresh_run_dir(output_dir)
    run_dir = prepare_output_dir(output_dir)
    input_value = (
        spec.inputs.project_file if spec.mode is Mode.TEMPLATE else spec.inputs.geometry_file
    )
    input_path = resolve_input_path(spec_path, input_value)
    assert input_path is not None
    snapshot = safe_join(run_dir, Path("inputs") / input_path.name)
    snapshot.parent.mkdir()
    shutil.copy2(input_path, snapshot)
    saved_spec = spec.model_copy(deep=True)
    input_field = "project_file" if spec.mode is Mode.TEMPLATE else "geometry_file"
    setattr(saved_spec.inputs, input_field, snapshot.relative_to(run_dir).as_posix())

    normalized_path = safe_join(run_dir, "normalized-simulation.yaml")
    normalized_path.write_text(dump_normalized_yaml(saved_spec), encoding="utf-8")
    plan = build_mechanical_plan(spec, spec_path, input_path)
    plan_path = safe_join(run_dir, "mechanical-plan.json")
    plan_path.write_text(json.dumps(plan, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    script_path = safe_join(run_dir, "generated-mechanical.py")
    script_path.write_text(render_script(plan), encoding="utf-8", newline="\n")
    environment_path = safe_join(run_dir, "environment.json")
    environment_path.write_text(
        json.dumps(environment_snapshot(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    manifest = initial_manifest(
        run_dir=run_dir,
        input_path=snapshot,
        spec_path=spec_path,
        normalized_path=normalized_path,
        script_path=script_path,
        execution_mode=spec.execution.backend,
        transport_mode=spec.execution.transport_mode,
    )
    manifest_path = safe_join(run_dir, "run-manifest.json")
    for path in (plan_path, environment_path, manifest_path, snapshot):
        add_artifact(manifest, run_dir, path)
    manifest["commands_and_checks"].append("schema validation")
    manifest["commands_and_checks"].append("deterministic Mechanical compilation")
    write_manifest(manifest_path, manifest)
    return {
        "run_directory": str(run_dir),
        "normalized_spec": str(normalized_path),
        "mechanical_plan": str(plan_path),
        "generated_script": str(script_path),
        "manifest": str(manifest_path),
        "environment": str(environment_path),
    }
