"""Deterministically compile a Mechanical execution script and run manifest."""

from __future__ import annotations

import base64
import json
from pathlib import Path

from ansys_skill.compiler.plan import build_mechanical_plan
from ansys_skill.manifest import (
    add_artifact,
    environment_snapshot,
    initial_manifest,
    write_manifest,
)
from ansys_skill.paths import prepare_output_dir, resolve_input_path, safe_join
from ansys_skill.schema import Mode, SimulationSpec, dump_normalized_yaml

SCRIPT_TEMPLATE = r'''# Generated by text-to-ansys. Do not edit this derived artifact.
from __future__ import print_function

import base64
import glob
import json
import math
import os
import traceback
import units

SENTINEL = "TEXT_TO_ANSYS_RESULT:"
PLAN = json.loads(base64.b64decode("__PLAN_BASE64__").decode("utf-8"))
MESSAGES = []
FACE_SELECTIONS = []
CREATED = {}
CREATED_SCOPES = {}
ANALYSIS_INFO = {}
OBJECT_TYPES = {}


class TextToAnsysError(RuntimeError):
    pass


class UnsupportedMechanicalApi(TextToAnsysError):
    pass


class MechanicalCompat(object):
    """All version-sensitive Mechanical object-model access lives here."""

    @staticmethod
    def exact_object(name):
        matches = list(DataModel.GetObjectsByName(name))
        if len(matches) != 1:
            raise TextToAnsysError(
                "Expected exactly one Mechanical object named {!r}; found {}".format(
                    name, len(matches)
                )
            )
        return matches[0]

    @staticmethod
    def assert_object_type(obj, expected, label):
        try:
            type_name = str(obj.GetType().Name)
        except Exception as exc:
            raise UnsupportedMechanicalApi(
                "Mechanical object type inspection is unavailable for {}: {}".format(label, exc)
            )
        normalized = "".join(character for character in type_name.lower() if character.isalnum())
        if normalized not in expected:
            raise TextToAnsysError(
                "{} expected object type {}; found {!r}".format(
                    label, sorted(expected), type_name
                )
            )
        OBJECT_TYPES[label] = type_name
        return obj

    @staticmethod
    def input_path():
        absolute = PLAN["input"]["absolute_path"]
        if os.path.isfile(absolute):
            return absolute
        candidate = os.path.join(os.getcwd(), PLAN["input"]["basename"])
        if os.path.isfile(candidate):
            return candidate
        raise TextToAnsysError("Mechanical input file is unavailable: {}".format(candidate))

    @staticmethod
    def tree_bodies():
        try:
            return list(
                DataModel.GetObjectsByType(
                    Ansys.Mechanical.DataModel.Enums.DataModelObjectCategory.Body
                )
            )
        except Exception as exc:
            raise UnsupportedMechanicalApi(
                "DataModel.GetObjectsByType(DataModelObjectCategory.Body) is unavailable: {}".format(exc)
            )

    @staticmethod
    def exact_tree_body(name):
        matches = [body for body in MechanicalCompat.tree_bodies() if str(body.Name) == name]
        if len(matches) != 1:
            raise TextToAnsysError(
                "Expected exactly one geometry body named {!r}; found {}".format(name, len(matches))
            )
        return matches[0]

    @staticmethod
    def geo_bodies():
        try:
            bodies = []
            for assembly in ExtAPI.DataModel.GeoData.Assemblies:
                for part in assembly.Parts:
                    bodies.extend(list(part.Bodies))
            return bodies
        except Exception as exc:
            raise UnsupportedMechanicalApi(
                "Geometry traversal API required by axis_extreme_face is unavailable: {}".format(exc)
            )

    @staticmethod
    def exact_geo_body(name):
        bodies = MechanicalCompat.geo_bodies()
        if name:
            matches = [body for body in bodies if str(body.Name) == name]
        else:
            matches = bodies
        if len(matches) != 1:
            raise TextToAnsysError(
                "axis_extreme_face requires exactly one matching body; found {} for {!r}".format(
                    len(matches), name
                )
            )
        return matches[0]

    @staticmethod
    def face_data(face, geometry_unit):
        try:
            centroid = [float(value) for value in face.Centroid]
            area = float(face.Area)
            uv = face.ParamAtPoint(face.Centroid)
            normal = [float(value) for value in face.NormalAtParam(uv[0], uv[1])]
            return {
                "id": int(face.Id),
                "centroid": centroid,
                "centroid_unit": geometry_unit,
                "area": area,
                "area_unit": "{}^2".format(geometry_unit),
                "normal": normal,
            }
        except Exception as exc:
            raise UnsupportedMechanicalApi(
                "IGeoFace Centroid/Area/ParamAtPoint/NormalAtParam API is unavailable: {}".format(exc)
            )

    @staticmethod
    def selection_from_entities(entities):
        try:
            selection = ExtAPI.SelectionManager.CreateSelectionInfo(
                Ansys.ACT.Interfaces.Common.SelectionTypeEnum.GeometryEntities
            )
            selection.Entities = list(entities)
            return selection
        except Exception as exc:
            raise UnsupportedMechanicalApi(
                "Geometry entity selection API is unavailable: {}".format(exc)
            )

    @staticmethod
    def set_components(load, values):
        load.DefineBy = Ansys.Mechanical.DataModel.Enums.LoadDefineBy.Components
        load.XComponent.Output.DiscreteValues = [Quantity(values[0])]
        load.YComponent.Output.DiscreteValues = [Quantity(values[1])]
        load.ZComponent.Output.DiscreteValues = [Quantity(values[2])]

    @staticmethod
    def set_directional_axis(result, axis):
        enum_name = {"x": "XAxis", "y": "YAxis", "z": "ZAxis"}[axis]
        try:
            result.NormalOrientation = getattr(
                Ansys.Mechanical.DataModel.Enums.NormalOrientationType, enum_name
            )
        except Exception as exc:
            raise UnsupportedMechanicalApi(
                "Directional deformation orientation API is unavailable: {}".format(exc)
            )

    @staticmethod
    def assert_static_structural(analysis):
        try:
            analysis_type = str(analysis.AnalysisType)
            physics_type = str(analysis.PhysicsType)
            analysis.AnalysisSettings.LargeDeflection = False
            large_deflection = bool(analysis.AnalysisSettings.LargeDeflection)
        except Exception as exc:
            raise UnsupportedMechanicalApi(
                "Analysis type or LargeDeflection API is unavailable: {}".format(exc)
            )
        if "static" not in analysis_type.lower() or "structural" not in physics_type.lower():
            raise TextToAnsysError(
                "Expected a static structural analysis; found AnalysisType={!r}, "
                "PhysicsType={!r}".format(analysis_type, physics_type)
            )
        if large_deflection:
            raise TextToAnsysError("LargeDeflection remained enabled; small-deformation solve blocked")
        return {
            "analysis_type": analysis_type,
            "physics_type": physics_type,
            "large_deflection": large_deflection,
        }


def scope_location(scope_id):
    if scope_id in CREATED_SCOPES:
        return CREATED_SCOPES[scope_id]
    scope = next(item for item in PLAN["scopes"] if item["id"] == scope_id)
    if scope["kind"] in ("named_selection", "object_name"):
        obj = MechanicalCompat.exact_object(scope["name"])
        if scope["kind"] == "named_selection":
            obj = MechanicalCompat.assert_object_type(
                obj, {"namedselection"}, "scope:{}".format(scope_id)
            )
        CREATED_SCOPES[scope_id] = obj
        return obj
    if scope["kind"] != "axis_extreme_face":
        raise TextToAnsysError("Unsupported scope kind: {}".format(scope["kind"]))

    body = MechanicalCompat.exact_geo_body(scope.get("body"))
    axis_index = {"x": 0, "y": 1, "z": 2}[scope["axis"]]
    try:
        geometry_unit = str(ExtAPI.DataModel.GeoData.Unit)
        tolerance = float(
            units.ConvertUnit(
                float(scope["tolerance_canonical_m"]),
                fromUnit="m",
                toUnit=geometry_unit,
            )
        )
    except Exception as exc:
        raise UnsupportedMechanicalApi(
            "Geometry unit conversion required by axis_extreme_face is unavailable: {}".format(exc)
        )
    entries = [
        (face, MechanicalCompat.face_data(face, geometry_unit)) for face in body.Faces
    ]
    if not entries:
        raise TextToAnsysError("axis_extreme_face found no faces")
    coordinates = [entry[1]["centroid"][axis_index] for entry in entries]
    target = min(coordinates) if scope["extreme"] == "min" else max(coordinates)
    candidates = [
        entry for entry in entries if abs(entry[1]["centroid"][axis_index] - target) <= tolerance
    ]
    FACE_SELECTIONS.append(
        {
            "scope_id": scope_id,
            "axis": scope["axis"],
            "extreme": scope["extreme"],
            "target": target,
            "geometry_length_unit": geometry_unit,
            "tolerance_original": scope["tolerance"],
            "tolerance_canonical_m": scope["tolerance_canonical_m"],
            "tolerance_geometry_unit": tolerance,
            "candidates": [entry[1] for entry in entries],
            "matched": [entry[1] for entry in candidates],
        }
    )
    if len(candidates) != 1:
        raise TextToAnsysError(
            "axis_extreme_face {!r} expected one face; found {}".format(scope_id, len(candidates))
        )
    selection = MechanicalCompat.selection_from_entities([candidates[0][0]])
    named_selection = Model.AddNamedSelection()
    named_selection.Name = scope["dpf_named_selection"]
    named_selection.Location = selection
    CREATED_SCOPES[scope_id] = named_selection
    return named_selection


def prepare_model():
    input_path = MechanicalCompat.input_path()
    if PLAN["mode"] == "template":
        App.open(input_path)
        analysis = MechanicalCompat.exact_object(PLAN["analysis"]["object_name"])
    else:
        App.new()
        geometry_import = Model.AddGeometryImportGroup().AddGeometryImport()
        preferences = Ansys.ACT.Mechanical.Utilities.GeometryImportPreferences()
        geometry_import.Import(
            input_path,
            Ansys.Mechanical.DataModel.Enums.GeometryImportPreference.Format.Automatic,
            preferences,
        )
        analysis = Model.AddStaticStructuralAnalysis()
        analysis.Name = "text-to-ansys static structural"
    ANALYSIS_INFO.update(MechanicalCompat.assert_static_structural(analysis))
    CREATED["analysis"] = analysis
    return analysis


def apply_materials():
    for body_plan in PLAN["bodies"]:
        if body_plan["material_source"] != "engineering_data":
            raise UnsupportedMechanicalApi(
                "Custom material authoring is intentionally disabled in v1"
            )
        body = MechanicalCompat.exact_tree_body(body_plan["name"])
        body.Material = body_plan["material_name"]


def apply_mesh():
    Model.Mesh.ElementSize = Quantity(PLAN["mesh"]["global_element_size"])
    order = PLAN["mesh"]["element_order"]
    if order != "program_controlled":
        try:
            Model.Mesh.ElementOrder = getattr(
                Ansys.Mechanical.DataModel.Enums.ElementOrder,
                "Linear" if order == "linear" else "Quadratic",
            )
        except Exception as exc:
            raise UnsupportedMechanicalApi("Mesh element-order API is unavailable: {}".format(exc))
    Model.Mesh.GenerateMesh()


def apply_supports(analysis):
    for item in PLAN["supports"]:
        if PLAN["mode"] == "template":
            support = MechanicalCompat.assert_object_type(
                MechanicalCompat.exact_object(item["object_name"]),
                {"fixedsupport"},
                "support:{}".format(item["id"]),
            )
        else:
            support = analysis.AddFixedSupport()
            support.Name = item["id"]
        support.Location = scope_location(item["scope"])
        CREATED[item["id"]] = support


def apply_loads(analysis):
    for item in PLAN["loads"]:
        if PLAN["mode"] == "template":
            expected = {
                "force": {"force"},
                "pressure": {"pressure"},
                "gravity": {"earthgravity"},
            }[item["type"]]
            load = MechanicalCompat.assert_object_type(
                MechanicalCompat.exact_object(item["object_name"]),
                expected,
                "load:{}".format(item["id"]),
            )
        elif item["type"] == "force":
            load = analysis.AddForce()
        elif item["type"] == "pressure":
            load = analysis.AddPressure()
        elif item["type"] == "gravity":
            load = analysis.AddEarthGravity()
        else:
            raise TextToAnsysError("Unsupported load type: {}".format(item["type"]))
        if PLAN["mode"] != "template":
            load.Name = item["id"]
        if item.get("scope"):
            load.Location = scope_location(item["scope"])
        if item["type"] == "force":
            MechanicalCompat.set_components(load, item["components"])
        elif item["type"] == "gravity":
            load.Direction = getattr(
                Ansys.Mechanical.DataModel.Enums.GravityOrientationType,
                item["gravity_orientation"],
            )
        else:
            load.Magnitude.Output.DiscreteValues = [Quantity(item["magnitude"])]
        CREATED[item["id"]] = load


def apply_results(analysis):
    solution = analysis.Solution
    for item in PLAN["requested_results"]:
        if item["type"] in ("solver_messages", "node_count", "element_count"):
            continue
        if PLAN["mode"] == "template":
            expected = {
                "total_deformation": {"totaldeformation"},
                "directional_deformation": {"directionaldeformation"},
                "equivalent_von_mises_stress": {"equivalentstress"},
                "reaction_force": {"forcereaction"},
            }[item["type"]]
            result = MechanicalCompat.assert_object_type(
                MechanicalCompat.exact_object(item["object_name"]),
                expected,
                "result:{}".format(item["id"]),
            )
        elif item["type"] == "total_deformation":
            result = solution.AddTotalDeformation()
        elif item["type"] == "directional_deformation":
            result = solution.AddDirectionalDeformation()
            MechanicalCompat.set_directional_axis(result, item["direction"])
        elif item["type"] == "equivalent_von_mises_stress":
            result = solution.AddEquivalentStress()
        elif item["type"] == "reaction_force":
            result = solution.AddForceReaction()
            result.BoundaryConditionSelection = CREATED[item["support"]]
        else:
            raise TextToAnsysError("Unsupported result type: {}".format(item["type"]))
        if PLAN["mode"] != "template":
            result.Name = item["id"]
        if item.get("scope") and hasattr(result, "Location"):
            result.Location = scope_location(item["scope"])
        CREATED[item["id"]] = result


def collect_messages():
    collected = []
    try:
        for message in ExtAPI.Application.Messages:
            collected.append(
                {
                    "severity": str(getattr(message, "Severity", "UNKNOWN")),
                    "text": str(getattr(message, "DisplayString", message)),
                }
            )
    except Exception as exc:
        collected.append({"severity": "UNKNOWN", "text": "Message API unavailable: {}".format(exc)})
    return collected


def export_current_image(filename):
    settings = Ansys.Mechanical.Graphics.GraphicsImageExportSettings()
    settings.Resolution = (
        Ansys.Mechanical.DataModel.Enums.GraphicsResolutionType.EnhancedResolution
    )
    settings.Background = Ansys.Mechanical.DataModel.Enums.GraphicsBackgroundType.White
    settings.CurrentGraphicsDisplay = True
    settings.Width = 1280
    settings.Height = 720
    ExtAPI.Graphics.ExportImage(
        os.path.join(os.getcwd(), filename),
        Ansys.Mechanical.DataModel.Enums.GraphicsImageExportFormat.PNG,
        settings,
    )


def export_images():
    states = []
    if not PLAN["output"].get("export_images"):
        return [{"name": "visual_review", "status": "NOT_RUN", "reason": "disabled"}]
    try:
        Model.Mesh.Activate()
        export_current_image("mesh.png")
        states.append({"name": "mesh.png", "status": "PASS"})
    except Exception as exc:
        states.append({"name": "mesh.png", "status": "NOT_RUN", "reason": str(exc)})
    for result_type, filename in (
        ("total_deformation", "total-deformation.png"),
        ("equivalent_von_mises_stress", "equivalent-stress.png"),
    ):
        item = next((x for x in PLAN["requested_results"] if x["type"] == result_type), None)
        if not item or item["id"] not in CREATED:
            states.append({"name": filename, "status": "NOT_RUN", "reason": "result not requested"})
            continue
        try:
            CREATED[item["id"]].Activate()
            export_current_image(filename)
            states.append({"name": filename, "status": "PASS"})
        except Exception as exc:
            states.append({"name": filename, "status": "NOT_RUN", "reason": str(exc)})
    return states


def write_artifacts(status, error=None):
    result_files = sorted(glob.glob(os.path.join(os.getcwd(), "**", "*.rst"), recursive=True))
    solve_logs = sorted(glob.glob(os.path.join(os.getcwd(), "**", "solve.out"), recursive=True))
    payload = {
        "status": status,
        "error": error,
        "face_selections": FACE_SELECTIONS,
        "analysis": ANALYSIS_INFO,
        "object_types": OBJECT_TYPES,
        "solver_messages": collect_messages(),
        "result_files": result_files,
        "solve_logs": solve_logs,
        "visual_review": export_images() if status == "SOLVED" else [],
    }
    with open(os.path.join(os.getcwd(), "mechanical-artifacts.json"), "w") as stream:
        json.dump(payload, stream, indent=2, sort_keys=True)
    with open(os.path.join(os.getcwd(), "face-selection-report.json"), "w") as stream:
        json.dump(FACE_SELECTIONS, stream, indent=2, sort_keys=True)
    return payload


outcome = None
try:
    analysis = prepare_model()
    apply_materials()
    apply_supports(analysis)
    apply_loads(analysis)
    apply_results(analysis)
    apply_mesh()
    analysis.Solve(True)
    if PLAN["output"].get("save_project"):
        ExtAPI.DataModel.Project.SaveAs(os.path.join(os.getcwd(), "text-to-ansys.mechdb"))
    outcome = write_artifacts("SOLVED")
except Exception as exc:
    outcome = write_artifacts(
        "FAILED",
        {"type": type(exc).__name__, "message": str(exc), "traceback": traceback.format_exc()},
    )

print(SENTINEL + json.dumps(outcome, sort_keys=True))
if outcome["status"] != "SOLVED":
    raise TextToAnsysError(outcome["error"]["message"])
'''


def render_script(plan: dict[str, object]) -> str:
    compact = json.dumps(plan, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    encoded = base64.b64encode(compact.encode("utf-8")).decode("ascii")
    return SCRIPT_TEMPLATE.replace("__PLAN_BASE64__", encoded)


def compile_simulation(
    spec: SimulationSpec, spec_path: Path, output_dir: str | Path
) -> dict[str, object]:
    run_dir = prepare_output_dir(output_dir)
    input_value = (
        spec.inputs.project_file if spec.mode is Mode.TEMPLATE else spec.inputs.geometry_file
    )
    input_path = resolve_input_path(spec_path, input_value)
    assert input_path is not None

    normalized_path = safe_join(run_dir, "normalized-simulation.yaml")
    normalized_path.write_text(dump_normalized_yaml(spec), encoding="utf-8")
    plan = build_mechanical_plan(spec, spec_path, input_path)
    plan_path = safe_join(run_dir, "mechanical-plan.json")
    plan_path.write_text(json.dumps(plan, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    script_path = safe_join(run_dir, "generated-mechanical.py")
    script_path.write_text(render_script(plan), encoding="utf-8", newline="\n")
    environment_path = safe_join(run_dir, "environment.json")
    environment_path.write_text(
        json.dumps(environment_snapshot(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    manifest = initial_manifest(
        run_dir=run_dir,
        input_path=input_path,
        spec_path=spec_path,
        normalized_path=normalized_path,
        script_path=script_path,
        execution_mode=spec.execution.backend,
        transport_mode=spec.execution.transport_mode,
    )
    manifest_path = safe_join(run_dir, "run-manifest.json")
    for path in (plan_path, environment_path, manifest_path):
        add_artifact(manifest, run_dir, path)
    manifest["commands_and_checks"].append("schema validation")
    manifest["commands_and_checks"].append("deterministic Mechanical compilation")
    write_manifest(manifest_path, manifest)
    return {
        "run_directory": str(run_dir),
        "normalized_spec": str(normalized_path),
        "mechanical_plan": str(plan_path),
        "generated_script": str(script_path),
        "manifest": str(manifest_path),
        "environment": str(environment_path),
    }
